apiVersion: apps/v1
kind: Deployment
metadata:
  name: technova-ms-vendor
  namespace: technova
  labels:
    app: technova-ms-vendor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: technova-ms-vendor
  template:
    metadata:
      labels:
        app: technova-ms-vendor
    spec:
      containers:
        - name: technova-ms-vendor
          image: gwrgwr/technova-ms-vendor:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI_MS_VENDOR
              value: "mongodb+srv://murilomassa72:t0SnsRhgENyGcKG9@technova.dvmjo4p.mongodb.net/technova-ms-vendor?retryWrites=true&w=majority&appName=Technova"
            - name: RABBITMQ_USER
              value: "admin"
            - name: RABBITMQ_PASS
              value: "admin"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"